services:

  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PORT: ${DB_PORT}
      MARIADB_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend_api
  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend_api

  network:
    backend_api:
      name: backend_api
      driver: bridge