services:

  db:
    image: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PORT: ${DB_PORT}
      MARIADB_HOST: ${DB_HOST}
    ports:
      - "${DB_PORT}:3306"
